name: Bug report
description: Report a bug to help us improve
title: "[BUG] "
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in the DjangoIndia community website! Please provide the details below.

  - type: input
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce:
      placeholder: How can the bug be reproduced?
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Expected behavior
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Actual behavior
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem.
      placeholder: Additional context

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the project is affected?
      options:
        - Frontend
        - Backend
        - Both
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Software version.
      placeholder: e.g., v1.0.0

  - type: input
    id: browser
    attributes:
      label: Browser (if frontend)
      description: Browser and version (if applicable).
      placeholder: e.g., Chrome 91.0
